import React from 'react'

const FeedBack = () => {
  return (
    <div id='feedback'>
      <div className="name">
      <h1>FEEDBACK</h1>
      </div>
      <div className="ms">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia optio inventore quis saepe modi temporibus enim laborum, provident ullam minima dolore quam asperiores quod! Illum magni incidunt sunt! Deleniti fuga et veniam quaerat natus officiis sed, nesciunt excepturi sint minima quis blanditiis quam. Aliquid, animi. Facere aperiam ea nam reprehenderit porro possimus, eveniet quis numquam a rem aliquid laudantium facilis beatae odit, voluptas itaque, ipsam quibusdam eligendi officia assumenda non. Consectetur natus adipisci impedit, ea sequi similique eos unde deserunt consequuntur quas assumenda distinctio quia ducimus, accusantium repellat atque. Cupiditate a quas numquam ipsum delectus sunt atque! Incidunt harum, maxime deleniti saepe optio ut odio magni adipisci officia, non molestiae voluptatem veritatis perspiciatis culpa natus. Quas tempora consectetur id ipsam earum neque at delectus, dicta magnam, perferendis illum iste inventore itaque quo facere sit natus odio voluptatibus est fuga eaque! Minus asperiores assumenda omnis ad accusantium atque debitis ipsum, laudantium repellendus, illo repudiandae ullam nisi quia vero voluptatibus sed dolores! Suscipit alias enim voluptates! Quidem, recusandae, quas suscipit quo quis molestiae quibusdam nostrum temporibus illum provident rem ab maxime. Minus iste animi labore optio eius provident vel eaque, deserunt cupiditate ratione cumque aliquid mollitia temporibus id repellendus. Cum illo corrupti natus corporis, molestias harum vitae reprehenderit at illum tempora fugiat? Odit culpa consequuntur dolor. Dignissimos eius libero ratione et, qui rem explicabo exercitationem aspernatur beatae possimus voluptates veniam recusandae at consequuntur inventore nobis laudantium? Qui similique obcaecati in quisquam! L
        aboriosam labore quod veritatis sunt praesentium voluptate perspiciatis provident! Ab quasi distinctio necessitatibus natus expedita. Facilis quo quibusdam aliquam assumenda maiores dolor reprehenderit fugiat pariatur necessitatibus tempore nam, dolores eius. Possimus dicta esse quos nemo iusto reiciendis ut, laudantium earum ullam nesciunt minus aperiam hic ex illum. Praesentium repellendus ullam repudiandae, inventore deleniti incidunt asperiores ad expedita consectetur quam architecto eos.
      </div>
      <div className="ms">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia optio inventore quis saepe modi temporibus enim laborum, provident ullam minima dolore quam asperiores quod! Illum magni incidunt sunt! Deleniti fuga et veniam quaerat natus officiis sed, nesciunt excepturi sint minima quis blanditiis quam. Aliquid, animi. Facere aperiam ea nam reprehenderit porro possimus, eveniet quis numquam a rem aliquid laudantium facilis beatae odit, voluptas itaque, ipsam quibusdam eligendi officia assumenda non. Consectetur natus adipisci impedit, ea sequi similique eos unde deserunt consequuntur quas assumenda distinctio quia ducimus, accusantium repellat atque. Cupiditate a quas numquam ipsum delectus sunt atque! Incidunt harum, maxime deleniti saepe optio ut odio magni adipisci officia, non molestiae voluptatem veritatis perspiciatis culpa natus. Quas tempora consectetur id ipsam earum neque at delectus, dicta magnam, perferendis illum iste inventore itaque quo facere sit natus odio voluptatibus est fuga eaque! Minus asperiores assumenda omnis ad accusantium atque debitis ipsum, laudantium repellendus, illo repudiandae ullam nisi quia vero voluptatibus sed dolores! Suscipit alias enim voluptates! Quidem, recusandae, quas suscipit quo quis molestiae quibusdam nostrum temporibus illum provident rem ab maxime. Minus iste animi labore optio eius provident vel eaque, deserunt cupiditate ratione cumque aliquid mollitia temporibus id repellendus. Cum illo corrupti natus corporis, molestias harum vitae reprehenderit at illum tempora fugiat? Odit culpa consequuntur dolor. Dignissimos eius libero ratione et, qui rem explicabo exercitationem aspernatur beatae possimus voluptates veniam recusandae at consequuntur inventore nobis laudantium? Qui similique obcaecati in quisquam! L
        aboriosam labore quod veritatis sunt praesentium voluptate perspiciatis provident! Ab quasi distinctio necessitatibus natus expedita. Facilis quo quibusdam aliquam assumenda maiores dolor reprehenderit fugiat pariatur necessitatibus tempore nam, dolores eius. Possimus dicta esse quos nemo iusto reiciendis ut, laudantium earum ullam nesciunt minus aperiam hic ex illum. Praesentium repellendus ullam repudiandae, inventore deleniti incidunt asperiores ad expedita consectetur quam architecto eos.
      </div>
      <div className="ms">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia optio inventore quis saepe modi temporibus enim laborum, provident ullam minima dolore quam asperiores quod! Illum magni incidunt sunt! Deleniti fuga et veniam quaerat natus officiis sed, nesciunt excepturi sint minima quis blanditiis quam. Aliquid, animi. Facere aperiam ea nam reprehenderit porro possimus, eveniet quis numquam a rem aliquid laudantium facilis beatae odit, voluptas itaque, ipsam quibusdam eligendi officia assumenda non. Consectetur natus adipisci impedit, ea sequi similique eos unde deserunt consequuntur quas assumenda distinctio quia ducimus, accusantium repellat atque. Cupiditate a quas numquam ipsum delectus sunt atque! Incidunt harum, maxime deleniti saepe optio ut odio magni adipisci officia, non molestiae voluptatem veritatis perspiciatis culpa natus. Quas tempora consectetur id ipsam earum neque at delectus, dicta magnam, perferendis illum iste inventore itaque quo facere sit natus odio voluptatibus est fuga eaque! Minus asperiores assumenda omnis ad accusantium atque debitis ipsum, laudantium repellendus, illo repudiandae ullam nisi quia vero voluptatibus sed dolores! Suscipit alias enim voluptates! Quidem, recusandae, quas suscipit quo quis molestiae quibusdam nostrum temporibus illum provident rem ab maxime. Minus iste animi labore optio eius provident vel eaque, deserunt cupiditate ratione cumque aliquid mollitia temporibus id repellendus. Cum illo corrupti natus corporis, molestias harum vitae reprehenderit at illum tempora fugiat? Odit culpa consequuntur dolor. Dignissimos eius libero ratione et, qui rem explicabo exercitationem aspernatur beatae possimus voluptates veniam recusandae at consequuntur inventore nobis laudantium? Qui similique obcaecati in quisquam! L
        aboriosam labore quod veritatis sunt praesentium voluptate perspiciatis provident! Ab quasi distinctio necessitatibus natus expedita. Facilis quo quibusdam aliquam assumenda maiores dolor reprehenderit fugiat pariatur necessitatibus tempore nam, dolores eius. Possimus dicta esse quos nemo iusto reiciendis ut, laudantium earum ullam nesciunt minus aperiam hic ex illum. Praesentium repellendus ullam repudiandae, inventore deleniti incidunt asperiores ad expedita consectetur quam architecto eos.
      </div>
    </div>
  )
}

export default FeedBack