import React from 'react'

const Shop = () => {
  return (
    <div  id='shop'>
      <div className="name">
        <h1>SHOP</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quod, ex repudiandae iure vel, doloremque, rem corporis accusamus iste alias facilis sapiente! Ea accusantium nostrum quod, enim rerum iure nemo reprehenderit minima corporis ex amet porro cumque vero et consectetur laboriosam asperiores repellat delectus voluptas ad ut consequatur necessitatibus! Id hic soluta ex laboriosam, in animi enim deleniti obcaecati tenetur et quaerat. Consequuntur excepturi, dolores praesentium necessitatibus distinctio vero quisquam commodi, quia sed quo blanditiis quis suscipit totam. Sed doloribus voluptas dolor deleniti saepe, officiis iusto quasi cum similique autem excepturi voluptatum, error corrupti est modi nobis. Accusamus iste consectetur maiores, earum, illum architecto similique ea rerum sunt, iure aut ex quisquam tenetur quo. Veritatis, veniam in totam maxime qui debitis accusamus illum amet voluptates asperiores ut. Dolorem earum, quia deleniti ipsam, nobis iste culpa facere praesentium vero sint repudiandae officia autem ratione sapiente aliquid ea beatae nam labore molestias! Sapiente veniam quis ab maxime debitis voluptate. In nihil modi repellendus provident quidem, ab asperiores pariatur. Illo voluptates temporibus tempora libero, sed autem nisi, obcaecati omnis itaque similique rerum! Quaerat beatae, obcaecati dignissimos dolores ullam nemo veniam sapiente, animi numquam sunt saepe aliquid blanditiis enim, 
          necessitatibus dolorum ipsam natus tenetur?</p>
      </div>
      <div className="name">
        <h1>Landlord</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quod, ex repudiandae iure vel, doloremque, rem corporis accusamus iste alias facilis sapiente! Ea accusantium nostrum quod, enim rerum iure nemo reprehenderit minima corporis ex amet porro cumque vero et consectetur laboriosam asperiores repellat delectus voluptas ad ut consequatur necessitatibus! Id hic soluta ex laboriosam, in animi enim deleniti obcaecati tenetur et quaerat. Consequuntur excepturi, dolores praesentium necessitatibus distinctio vero quisquam commodi, quia sed quo blanditiis quis suscipit totam. Sed doloribus voluptas dolor deleniti saepe, officiis iusto quasi cum similique autem excepturi voluptatum, error corrupti est modi nobis. Accusamus iste consectetur maiores, earum, illum architecto similique ea rerum sunt, iure aut ex quisquam tenetur quo. Veritatis, veniam in totam maxime qui debitis accusamus illum amet voluptates asperiores ut. Dolorem earum, quia deleniti ipsam, nobis iste culpa facere praesentium vero sint repudiandae officia autem ratione sapiente aliquid ea beatae nam labore molestias! Sapiente veniam quis ab maxime debitis voluptate. In nihil modi repellendus provident quidem, ab asperiores pariatur. Illo voluptates temporibus tempora libero, sed autem nisi, obcaecati omnis itaque similique rerum! Quaerat beatae, obcaecati dignissimos dolores ullam nemo veniam sapiente, animi numquam sunt saepe aliquid blanditiis enim, 
          necessitatibus dolorum ipsam natus tenetur?</p>
      </div>
      <div className="name">
        <h1>Landlord</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quod, ex repudiandae iure vel, doloremque, rem corporis accusamus iste alias facilis sapiente! Ea accusantium nostrum quod, enim rerum iure nemo reprehenderit minima corporis ex amet porro cumque vero et consectetur laboriosam asperiores repellat delectus voluptas ad ut consequatur necessitatibus! Id hic soluta ex laboriosam, in animi enim deleniti obcaecati tenetur et quaerat. Consequuntur excepturi, dolores praesentium necessitatibus distinctio vero quisquam commodi, quia sed quo blanditiis quis suscipit totam. Sed doloribus voluptas dolor deleniti saepe, officiis iusto quasi cum similique autem excepturi voluptatum, error corrupti est modi nobis. Accusamus iste consectetur maiores, earum, illum architecto similique ea rerum sunt, iure aut ex quisquam tenetur quo. Veritatis, veniam in totam maxime qui debitis accusamus illum amet voluptates asperiores ut. Dolorem earum, quia deleniti ipsam, nobis iste culpa facere praesentium vero sint repudiandae officia autem ratione sapiente aliquid ea beatae nam labore molestias! Sapiente veniam quis ab maxime debitis voluptate. In nihil modi repellendus provident quidem, ab asperiores pariatur. Illo voluptates temporibus tempora libero, sed autem nisi, obcaecati omnis itaque similique rerum! Quaerat beatae, obcaecati dignissimos dolores ullam nemo veniam sapiente, animi numquam sunt saepe aliquid blanditiis enim, 
          necessitatibus dolorum ipsam natus tenetur?</p>
      </div>
      <div className="name">
        <h1>Landlord</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quod, ex repudiandae iure vel, doloremque, rem corporis accusamus iste alias facilis sapiente! Ea accusantium nostrum quod, enim rerum iure nemo reprehenderit minima corporis ex amet porro cumque vero et consectetur laboriosam asperiores repellat delectus voluptas ad ut consequatur necessitatibus! Id hic soluta ex laboriosam, in animi enim deleniti obcaecati tenetur et quaerat. Consequuntur excepturi, dolores praesentium necessitatibus distinctio vero quisquam commodi, quia sed quo blanditiis quis suscipit totam. Sed doloribus voluptas dolor deleniti saepe, officiis iusto quasi cum similique autem excepturi voluptatum, error corrupti est modi nobis. Accusamus iste consectetur maiores, earum, illum architecto similique ea rerum sunt, iure aut ex quisquam tenetur quo. Veritatis, veniam in totam maxime qui debitis accusamus illum amet voluptates asperiores ut. Dolorem earum, quia deleniti ipsam, nobis iste culpa facere praesentium vero sint repudiandae officia autem ratione sapiente aliquid ea beatae nam labore molestias! Sapiente veniam quis ab maxime debitis voluptate. In nihil modi repellendus provident quidem, ab asperiores pariatur. Illo voluptates temporibus tempora libero, sed autem nisi, obcaecati omnis itaque similique rerum! Quaerat beatae, obcaecati dignissimos dolores ullam nemo veniam sapiente, animi numquam sunt saepe aliquid blanditiis enim, 
          necessitatibus dolorum ipsam natus tenetur?</p>
      </div>
      <div className="name">
        <h1>Landlord</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quod, ex repudiandae iure vel, doloremque, rem corporis accusamus iste alias facilis sapiente! Ea accusantium nostrum quod, enim rerum iure nemo reprehenderit minima corporis ex amet porro cumque vero et consectetur laboriosam asperiores repellat delectus voluptas ad ut consequatur necessitatibus! Id hic soluta ex laboriosam, in animi enim deleniti obcaecati tenetur et quaerat. Consequuntur excepturi, dolores praesentium necessitatibus distinctio vero quisquam commodi, quia sed quo blanditiis quis suscipit totam. Sed doloribus voluptas dolor deleniti saepe, officiis iusto quasi cum similique autem excepturi voluptatum, error corrupti est modi nobis. Accusamus iste consectetur maiores, earum, illum architecto similique ea rerum sunt, iure aut ex quisquam tenetur quo. Veritatis, veniam in totam maxime qui debitis accusamus illum amet voluptates asperiores ut. Dolorem earum, quia deleniti ipsam, nobis iste culpa facere praesentium vero sint repudiandae officia autem ratione sapiente aliquid ea beatae nam labore molestias! Sapiente veniam quis ab maxime debitis voluptate. In nihil modi repellendus provident quidem, ab asperiores pariatur. Illo voluptates temporibus tempora libero, sed autem nisi, obcaecati omnis itaque similique rerum! Quaerat beatae, obcaecati dignissimos dolores ullam nemo veniam sapiente, animi numquam sunt saepe aliquid blanditiis enim, 
          necessitatibus dolorum ipsam natus tenetur?</p>
      </div>
      <div className="name" id='chandan'> 
        <h1>CHandan</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quod, ex repudiandae iure vel, doloremque, rem corporis accusamus iste alias facilis sapiente! Ea accusantium nostrum quod, enim rerum iure nemo reprehenderit minima corporis ex amet porro cumque vero et consectetur laboriosam asperiores repellat delectus voluptas ad ut consequatur necessitatibus! Id hic soluta ex laboriosam, in animi enim deleniti obcaecati tenetur et quaerat. Consequuntur excepturi, dolores praesentium necessitatibus distinctio vero quisquam commodi, quia sed quo blanditiis quis suscipit totam. Sed doloribus voluptas dolor deleniti saepe, officiis iusto quasi cum similique autem excepturi voluptatum, error corrupti est modi nobis. Accusamus iste consectetur maiores, earum, illum architecto similique ea rerum sunt, iure aut ex quisquam tenetur quo. Veritatis, veniam in totam maxime qui debitis accusamus illum amet voluptates asperiores ut. Dolorem earum, quia deleniti ipsam, nobis iste culpa facere praesentium vero sint repudiandae officia autem ratione sapiente aliquid ea beatae nam labore molestias! Sapiente veniam quis ab maxime debitis voluptate. In nihil modi repellendus provident quidem, ab asperiores pariatur. Illo voluptates temporibus tempora libero, sed autem nisi, obcaecati omnis itaque similique rerum! Quaerat beatae, obcaecati dignissimos dolores ullam nemo veniam sapiente, animi numquam sunt saepe aliquid blanditiis enim, 
          necessitatibus dolorum ipsam natus tenetur?</p>
      </div>
    </div>
  )
}

export default Shop